Added Item Page
Current changes and modifications now include setting scenes and switching from Main View Page, Add Item Page, and Delete Item Page.

Error: File Not Found despite correct directory/file path [Will Fix ASAP]